// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ping.proto

#include "Ping.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace session {
PROTOBUF_CONSTEXPR C_Ping::C_Ping(
    ::_pbi::ConstantInitialized)
  : created_at_(nullptr)
  , session_id_(uint64_t{0u})
  , server_to_client_interval_(uint64_t{0u}){}
struct C_PingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_PingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_PingDefaultTypeInternal() {}
  union {
    C_Ping _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_PingDefaultTypeInternal _C_Ping_default_instance_;
PROTOBUF_CONSTEXPR S_Ping::S_Ping(
    ::_pbi::ConstantInitialized)
  : created_at_(nullptr)
  , session_id_(uint64_t{0u})
  , client_to_server_interval_(uint64_t{0u}){}
struct S_PingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_PingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_PingDefaultTypeInternal() {}
  union {
    S_Ping _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_PingDefaultTypeInternal _S_Ping_default_instance_;
}  // namespace session
static ::_pb::Metadata file_level_metadata_Ping_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_Ping_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_Ping_2eproto = nullptr;

const uint32_t TableStruct_Ping_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::session::C_Ping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::session::C_Ping, session_id_),
  PROTOBUF_FIELD_OFFSET(::session::C_Ping, created_at_),
  PROTOBUF_FIELD_OFFSET(::session::C_Ping, server_to_client_interval_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::session::S_Ping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::session::S_Ping, session_id_),
  PROTOBUF_FIELD_OFFSET(::session::S_Ping, created_at_),
  PROTOBUF_FIELD_OFFSET(::session::S_Ping, client_to_server_interval_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::session::C_Ping)},
  { 9, -1, -1, sizeof(::session::S_Ping)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::session::_C_Ping_default_instance_._instance,
  &::session::_S_Ping_default_instance_._instance,
};

const char descriptor_table_protodef_Ping_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\nPing.proto\022\007session\032\nEnum.proto\032\014Struc"
  "t.proto\"g\n\006C_Ping\022\022\n\nsession_id\030\001 \001(\004\022&\n"
  "\ncreated_at\030\002 \001(\0132\022.message.Timestamp\022!\n"
  "\031server_to_client_interval\030\003 \001(\004\"g\n\006S_Pi"
  "ng\022\022\n\nsession_id\030\001 \001(\004\022&\n\ncreated_at\030\002 \001"
  "(\0132\022.message.Timestamp\022!\n\031client_to_serv"
  "er_interval\030\003 \001(\004b\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_Ping_2eproto_deps[2] = {
  &::descriptor_table_Enum_2eproto,
  &::descriptor_table_Struct_2eproto,
};
static ::_pbi::once_flag descriptor_table_Ping_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_Ping_2eproto = {
    false, false, 265, descriptor_table_protodef_Ping_2eproto,
    "Ping.proto",
    &descriptor_table_Ping_2eproto_once, descriptor_table_Ping_2eproto_deps, 2, 2,
    schemas, file_default_instances, TableStruct_Ping_2eproto::offsets,
    file_level_metadata_Ping_2eproto, file_level_enum_descriptors_Ping_2eproto,
    file_level_service_descriptors_Ping_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_Ping_2eproto_getter() {
  return &descriptor_table_Ping_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_Ping_2eproto(&descriptor_table_Ping_2eproto);
namespace session {

// ===================================================================

class C_Ping::_Internal {
 public:
  static const ::message::Timestamp& created_at(const C_Ping* msg);
};

const ::message::Timestamp&
C_Ping::_Internal::created_at(const C_Ping* msg) {
  return *msg->created_at_;
}
void C_Ping::clear_created_at() {
  if (GetArenaForAllocation() == nullptr && created_at_ != nullptr) {
    delete created_at_;
  }
  created_at_ = nullptr;
}
C_Ping::C_Ping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:session.C_Ping)
}
C_Ping::C_Ping(const C_Ping& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_created_at()) {
    created_at_ = new ::message::Timestamp(*from.created_at_);
  } else {
    created_at_ = nullptr;
  }
  ::memcpy(&session_id_, &from.session_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&server_to_client_interval_) -
    reinterpret_cast<char*>(&session_id_)) + sizeof(server_to_client_interval_));
  // @@protoc_insertion_point(copy_constructor:session.C_Ping)
}

inline void C_Ping::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&created_at_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&server_to_client_interval_) -
    reinterpret_cast<char*>(&created_at_)) + sizeof(server_to_client_interval_));
}

C_Ping::~C_Ping() {
  // @@protoc_insertion_point(destructor:session.C_Ping)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_Ping::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete created_at_;
}

void C_Ping::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void C_Ping::Clear() {
// @@protoc_insertion_point(message_clear_start:session.C_Ping)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && created_at_ != nullptr) {
    delete created_at_;
  }
  created_at_ = nullptr;
  ::memset(&session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&server_to_client_interval_) -
      reinterpret_cast<char*>(&session_id_)) + sizeof(server_to_client_interval_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_Ping::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .message.Timestamp created_at = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_created_at(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 server_to_client_interval = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          server_to_client_interval_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_Ping::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:session.C_Ping)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 session_id = 1;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_session_id(), target);
  }

  // .message.Timestamp created_at = 2;
  if (this->_internal_has_created_at()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::created_at(this),
        _Internal::created_at(this).GetCachedSize(), target, stream);
  }

  // uint64 server_to_client_interval = 3;
  if (this->_internal_server_to_client_interval() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_server_to_client_interval(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:session.C_Ping)
  return target;
}

size_t C_Ping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:session.C_Ping)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .message.Timestamp created_at = 2;
  if (this->_internal_has_created_at()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *created_at_);
  }

  // uint64 session_id = 1;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // uint64 server_to_client_interval = 3;
  if (this->_internal_server_to_client_interval() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_server_to_client_interval());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_Ping::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    C_Ping::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_Ping::GetClassData() const { return &_class_data_; }

void C_Ping::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<C_Ping *>(to)->MergeFrom(
      static_cast<const C_Ping &>(from));
}


void C_Ping::MergeFrom(const C_Ping& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:session.C_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_created_at()) {
    _internal_mutable_created_at()->::message::Timestamp::MergeFrom(from._internal_created_at());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_server_to_client_interval() != 0) {
    _internal_set_server_to_client_interval(from._internal_server_to_client_interval());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_Ping::CopyFrom(const C_Ping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:session.C_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_Ping::IsInitialized() const {
  return true;
}

void C_Ping::InternalSwap(C_Ping* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_Ping, server_to_client_interval_)
      + sizeof(C_Ping::server_to_client_interval_)
      - PROTOBUF_FIELD_OFFSET(C_Ping, created_at_)>(
          reinterpret_cast<char*>(&created_at_),
          reinterpret_cast<char*>(&other->created_at_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C_Ping::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Ping_2eproto_getter, &descriptor_table_Ping_2eproto_once,
      file_level_metadata_Ping_2eproto[0]);
}

// ===================================================================

class S_Ping::_Internal {
 public:
  static const ::message::Timestamp& created_at(const S_Ping* msg);
};

const ::message::Timestamp&
S_Ping::_Internal::created_at(const S_Ping* msg) {
  return *msg->created_at_;
}
void S_Ping::clear_created_at() {
  if (GetArenaForAllocation() == nullptr && created_at_ != nullptr) {
    delete created_at_;
  }
  created_at_ = nullptr;
}
S_Ping::S_Ping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  // @@protoc_insertion_point(arena_constructor:session.S_Ping)
}
S_Ping::S_Ping(const S_Ping& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_created_at()) {
    created_at_ = new ::message::Timestamp(*from.created_at_);
  } else {
    created_at_ = nullptr;
  }
  ::memcpy(&session_id_, &from.session_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&client_to_server_interval_) -
    reinterpret_cast<char*>(&session_id_)) + sizeof(client_to_server_interval_));
  // @@protoc_insertion_point(copy_constructor:session.S_Ping)
}

inline void S_Ping::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&created_at_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&client_to_server_interval_) -
    reinterpret_cast<char*>(&created_at_)) + sizeof(client_to_server_interval_));
}

S_Ping::~S_Ping() {
  // @@protoc_insertion_point(destructor:session.S_Ping)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_Ping::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete created_at_;
}

void S_Ping::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void S_Ping::Clear() {
// @@protoc_insertion_point(message_clear_start:session.S_Ping)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && created_at_ != nullptr) {
    delete created_at_;
  }
  created_at_ = nullptr;
  ::memset(&session_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&client_to_server_interval_) -
      reinterpret_cast<char*>(&session_id_)) + sizeof(client_to_server_interval_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_Ping::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint64 session_id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          session_id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .message.Timestamp created_at = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_created_at(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // uint64 client_to_server_interval = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          client_to_server_interval_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_Ping::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:session.S_Ping)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint64 session_id = 1;
  if (this->_internal_session_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(1, this->_internal_session_id(), target);
  }

  // .message.Timestamp created_at = 2;
  if (this->_internal_has_created_at()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::created_at(this),
        _Internal::created_at(this).GetCachedSize(), target, stream);
  }

  // uint64 client_to_server_interval = 3;
  if (this->_internal_client_to_server_interval() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(3, this->_internal_client_to_server_interval(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:session.S_Ping)
  return target;
}

size_t S_Ping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:session.S_Ping)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .message.Timestamp created_at = 2;
  if (this->_internal_has_created_at()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *created_at_);
  }

  // uint64 session_id = 1;
  if (this->_internal_session_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_session_id());
  }

  // uint64 client_to_server_interval = 3;
  if (this->_internal_client_to_server_interval() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_client_to_server_interval());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_Ping::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    S_Ping::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_Ping::GetClassData() const { return &_class_data_; }

void S_Ping::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<S_Ping *>(to)->MergeFrom(
      static_cast<const S_Ping &>(from));
}


void S_Ping::MergeFrom(const S_Ping& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:session.S_Ping)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_created_at()) {
    _internal_mutable_created_at()->::message::Timestamp::MergeFrom(from._internal_created_at());
  }
  if (from._internal_session_id() != 0) {
    _internal_set_session_id(from._internal_session_id());
  }
  if (from._internal_client_to_server_interval() != 0) {
    _internal_set_client_to_server_interval(from._internal_client_to_server_interval());
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_Ping::CopyFrom(const S_Ping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:session.S_Ping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_Ping::IsInitialized() const {
  return true;
}

void S_Ping::InternalSwap(S_Ping* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_Ping, client_to_server_interval_)
      + sizeof(S_Ping::client_to_server_interval_)
      - PROTOBUF_FIELD_OFFSET(S_Ping, created_at_)>(
          reinterpret_cast<char*>(&created_at_),
          reinterpret_cast<char*>(&other->created_at_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S_Ping::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_Ping_2eproto_getter, &descriptor_table_Ping_2eproto_once,
      file_level_metadata_Ping_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace session
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::session::C_Ping*
Arena::CreateMaybeMessage< ::session::C_Ping >(Arena* arena) {
  return Arena::CreateMessageInternal< ::session::C_Ping >(arena);
}
template<> PROTOBUF_NOINLINE ::session::S_Ping*
Arena::CreateMaybeMessage< ::session::S_Ping >(Arena* arena) {
  return Arena::CreateMessageInternal< ::session::S_Ping >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
