#include "JK1LogChannels.h"

DEFINE_LOG_CATEGORY(LogSystem)
DEFINE_LOG_CATEGORY(LogCreature)
DEFINE_LOG_CATEGORY(LogPlayerCharacter)
DEFINE_LOG_CATEGORY(LogMonster)
DEFINE_LOG_CATEGORY(LogWarrior)
DEFINE_LOG_CATEGORY(LogAssassin)
DEFINE_LOG_CATEGORY(LogArchor)